### ISSUE TITLE
We are charging plans with a bad concept name

### ISSUE THREAD

**Issue by dmarvp** [bespoken/stripe-api#19]
**Preconditions**
On dashboard, have enough monitored skills to get the payment modal opened when enabling one more.

**Steps To Reproduce**
1. Go to Validation on a source
2. Click on Enable monitoring
3. Subscribe to a standard or pro plan.

**Expected behavior**
I'm subscribed correctly and I see that a charge has been made to my credit card in the name of "Bespoken - <Name of the plan> plan monthly subscription" e.g. *"Bespoken - Pro Plan Monthly Subscription"*.

**Actual behavior**
I'm subscribed correctly but I see that a charge has been made to my credit card in name of "STANDARD PLAN SERVICES"

**Screenshots**
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/6411740/44819702-71b54180-abb3-11e8-916b-46adbd880282.png">

**Additional Context**
If the concept can't be dynamic then just change it to: "Bespoken - Monthly Subscription"

**Comment by daisyzarzo** [comment]
the configuration was made
In the following link 
https://dashboard.stripe.com/subscriptions/products/prod_D2kuipV8qKUBNa

![image](https://user-images.githubusercontent.com/36684960/44935267-9cc79e80-ad35-11e8-9baa-d08bbed81990.png)

![image](https://user-images.githubusercontent.com/36684960/44935308-c385d500-ad35-11e8-863b-fd4146ee0cae.png)

Also, we're working as a team, so I'm adding access to more members

![image](https://user-images.githubusercontent.com/36684960/44935379-119ad880-ad36-11e8-9a74-4d39acc8084d.png)

**Comment by dmarvp** [comment]
@MKen-li this didn't require a code change, but we do need to test that these changes have taken effect when subscribing to stripe.

**Comment by MKen-li** [comment]
Marked as verified
Build dev-120
